# -*- coding: utf-8 -*-
"""Ml week 2 task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gXhnu7ys0JO-JiqfG5zOsZNJMsCHTWaz
"""

# =====================================================
# Week 2 - Data Preprocessing and Cleaning Pipeline
# Dataset: Teen_Mental_Health_Dataset.csv
# =====================================================

# Import Required Libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

# =====================================================
# Step 1: Load the Dataset
# =====================================================

# Load dataset
file_path = 'Teen_Mental_Health_Dataset.csv'
df = pd.read_csv("Teen_Mental_Health_Dataset.csv")

# Display first 5 rows
print("\nFirst 5 Rows of Dataset:")
print(df.head())

# Dataset shape
print("\nDataset Shape (Rows, Columns):")
print(df.shape)

# Column names
print("\nColumn Names:")
print(df.columns)

# Data types
print("\nData Types:")
print(df.dtypes)

# General dataset information
print("\nDataset Information:")
print(df.info())

# =====================================================
# Step 2: Identify Missing Values
# =====================================================

# Check missing values in each column
print("\nMissing Values in Each Column:")
print(df.isnull().sum())

# Total missing values
print("\nTotal Missing Values in Dataset:")
print(df.isnull().sum().sum())

# =====================================================
# Step 3: Handle Missing Values
# =====================================================

# Separate numerical and categorical columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = df.select_dtypes(include=['object']).columns

# Display numerical columns
print("\nNumerical Columns:")
print(numerical_cols)

# Display categorical columns
print("\nCategorical Columns:")
print(categorical_cols)

# Fill missing values in numerical columns using mean
for col in numerical_cols:
    df[col].fillna(df[col].mean(), inplace=True)

# Fill missing values in categorical columns using mode
for col in categorical_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

# Verify missing values again
print("\nMissing Values After Cleaning:")
print(df.isnull().sum())

# =====================================================
# Step 4: Remove Duplicate Records
# =====================================================

# Count duplicate rows
print("\nDuplicate Rows Before Removal:")
print(df.duplicated().sum())

# Remove duplicate rows
df = df.drop_duplicates()

# Verify duplicate removal
print("\nDuplicate Rows After Removal:")
print(df.duplicated().sum())

# =====================================================
# Step 5: Handle Categorical Data
# =====================================================

# Create LabelEncoder object
label_encoder = LabelEncoder()

# Convert categorical columns into numerical values
for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

# Display dataset after encoding
print("\nDataset After Label Encoding:")
print(df.head())

# =====================================================
# Step 6: Feature Scaling
# =====================================================

# Create StandardScaler object
scaler = StandardScaler()

# Scale numerical columns
scaled_features = scaler.fit_transform(df[numerical_cols])

# Convert scaled data into DataFrame
scaled_df = pd.DataFrame(scaled_features, columns=numerical_cols)

# Replace original numerical columns with scaled values
for col in numerical_cols:
    df[col] = scaled_df[col]

# Display dataset after scaling
print("\nDataset After Feature Scaling:")
print(df.head())

# =====================================================
# Step 7: Save the Cleaned Dataset
# =====================================================

# Save cleaned dataset
cleaned_file_name = 'cleaned_dataset.csv'
df.to_csv(cleaned_file_name, index=False)

print("\nCleaned dataset saved successfully as:", cleaned_file_name)

# =====================================================
# Final Verification
# =====================================================

# Final dataset shape
print("\nFinal Dataset Shape:")
print(df.shape)

# Display final dataset preview
print("\nFinal Dataset Preview:")
print(df.head())

# =====================================================
# Conclusion
# =====================================================

print("\nData preprocessing completed successfully!")
print("Raw Data → Clean Data → Prepared Data")